{
 "title": "Recom.live RNN",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Documents and Persons caches hit ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "asPercent(#B, #A)",
     "targetFull": "asPercent(recomlive.documents_cache_hit.sum_per_10s, recomlive.record_call.sum_per_10s)"
    },
    {
     "refCount": 1,
     "target": "asPercent(#D, #A)",
     "targetFull": "asPercent(recomlive.persons_cache_hit.sum_per_10s, recomlive.record_call.sum_per_10s)"
    }
   ]
  },
  {
   "title": "RNN loss",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "recomlive.rnn_loss.avg_per_10s" }
   ]
  },
  {
   "title": "Recommendation guess ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "asPercent(#B, #A)",
     "targetFull": "asPercent(recomlive.recommendation_hit.sum_per_10s, recomlive.recommend_call.sum_per_10s)"
    }
   ]
  }
 ]
}